### ISSUE TITLE
Example doesn't compile

### ISSUE THREAD

**Issue by redzic** [rust-av/ivf-rs#19] opened 2021-04-09 00:37 UTC
Hi, I get errors when trying to compile the example `remuxer.rs`.

Error:
```
   Compiling av-ivf v0.2.1
error[E0053]: method `write_packet` has an incompatible type for trait
   --> /home/redzic/.cargo/registry/src/github.com-1ecc6299db9ec823/av-ivf-0.2.1/src/muxer.rs:114:5
    |
114 |     fn write_packet(&mut self, buf: &mut dyn Write, pkt: Arc<Packet>) -> Result<()> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `av_data::packet::Packet`, found struct `Packet`
    |
    = note: expected fn pointer `fn(&mut IvfMuxer, &mut dyn std::io::Write, Arc<av_data::packet::Packet>) -> std::result::Result<_, _>`
               found fn pointer `fn(&mut IvfMuxer, &mut dyn std::io::Write, Arc<Packet>) -> std::result::Result<_, _>`
    = note: perhaps two different versions of crate `av_data` are being used?

error[E0053]: method `set_option` has an incompatible type for trait
   --> /home/redzic/.cargo/registry/src/github.com-1ecc6299db9ec823/av-ivf-0.2.1/src/muxer.rs:137:5
    |
137 |     fn set_option<'a>(&mut self, _key: &str, _val: Value<'a>) -> Result<()> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `av_data::value::Value`, found enum `Value`
    |
    = note: expected fn pointer `fn(&mut IvfMuxer, &str, av_data::value::Value<'a>) -> std::result::Result<_, _>`
               found fn pointer `fn(&mut IvfMuxer, &str, Value<'_>) -> std::result::Result<_, _>`
    = note: perhaps two different versions of crate `av_data` are being used?

error[E0308]: mismatched types
  --> /home/redzic/.cargo/registry/src/github.com-1ecc6299db9ec823/av-ivf-0.2.1/src/demuxer.rs:63:29
   |
63 |                       params: CodecParams {
   |  _____________________________^
64 | |                         extradata: None,
65 | |                         bit_rate: header.rate as usize,
66 | |                         delay: 0,
...  |
73 | |                         })),
74 | |                     },
   | |_____________________^ expected struct `av_data::params::CodecParams`, found struct `CodecParams`
   |
   = note: perhaps two different versions of crate `av_data` are being used?

error[E0308]: mismatched types
   --> /home/redzic/.cargo/registry/src/github.com-1ecc6299db9ec823/av-ivf-0.2.1/src/demuxer.rs:116:42
    |
116 |                         Event::NewPacket(pkt),
    |                                          ^^^ expected struct `av_data::packet::Packet`, found struct `Packet`
    |
    = note: perhaps two different versions of crate `av_data` are being used?

error[E0308]: mismatched types
  --> /home/redzic/.cargo/registry/src/github.com-1ecc6299db9ec823/av-ivf-0.2.1/src/muxer.rs:60:29
   |
60 |                 if let Some(MediaKind::Video(video)) = &params.kind {
   |                             ^^^^^^^^^^^^^^^^^^^^^^^    ------------ this expression has type `&Option<av_data::params::MediaKind>`
   |                             |
   |                             expected enum `av_data::params::MediaKind`, found a different enum `av_data::params::MediaKind`
   |
   = note: perhaps two different versions of crate `av_data` are being used?

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0053, E0308.
For more information about an error, try `rustc --explain E0053`.
error: could not compile `av-ivf`
```

```
$ rustc -V
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

Relevant section of Cargo.toml:
```
[dependencies]
log = "0.4.14"
av-format = "0.3.0"
av-ivf = "0.2.1"
structopt = "0.3.21"
```

**Comment by redzic** [comment] 2021-04-09 15:49
This seems to be fixed using latest git version of the `av-ivf` crate. So, the Cargo.toml looks like this:
```
[dependencies]
log = "0.4.14"
av-format = "0.3.0"
av-ivf = { git = "https://github.com/rust-av/ivf-rs" }
structopt = "0.3.21"
pretty_env_logger = "0.4.0"
```
Maybe a new release for this crate could be published to crates.io?

**Comment by Luni-4** [comment] 2022-06-29 18:25
@shssoichiro and @lu-zero 

Can we bump a new version on `crates.io`?

**Comment by lu-zero** [comment] 2022-06-29 19:34
remind me tomorrow and I'll do :)

**Comment by shssoichiro** [comment] 2022-06-29 22:12
Is this not fixed in 0.3.0 (the version I released last night)? It looked like there were no changes to actual code in your commit this morning @Luni-4, only to tests and examples.

**Comment by Luni-4** [comment] 2022-06-30 07:38
@shssoichiro Oh, true. 

@redzic could you please verify whether the problem is fixed for you?

**Closed as completed** 2022-07-05 13:16 UTC

**Comment by redzic** [comment] 2022-07-05 17:03
Sorry for the late response 😅. Yeah the example does indeed compile now, thanks!
